import { serviceSchema } from '@/domain/service/service.schema'

import { DEMO_WORKSPACE_ID } from './workspaces'

export const demoServices = serviceSchema.array().parse([
  {
    id: 'checkout-api',
    name: 'checkout-api',
    description: 'Handles checkout sessions and order creation',
    status: 'degraded',
    teamId: 'team-payments',
    workspaceId: DEMO_WORKSPACE_ID,
    environment: 'production',
    repositoryUrl: null,
    createdAt: '2026-01-10T09:00:00.000Z',
  },
  {
    id: 'payments-api',
    name: 'payments-api',
    description: 'Processes payment authorizations and captures',
    status: 'healthy',
    teamId: 'team-payments',
    workspaceId: DEMO_WORKSPACE_ID,
    environment: 'production',
    repositoryUrl: null,
    createdAt: '2026-01-10T09:00:00.000Z',
  },
  {
    id: 'billing-worker',
    name: 'billing-worker',
    description: 'Processes invoices and billing events',
    status: 'healthy',
    teamId: 'team-payments',
    workspaceId: DEMO_WORKSPACE_ID,
    environment: 'production',
    repositoryUrl: null,
    createdAt: '2026-01-10T09:00:00.000Z',
  },
  {
    id: 'auth-service',
    name: 'auth-service',
    description: 'Authenticates users and manages sessions',
    status: 'healthy',
    teamId: 'team-identity',
    workspaceId: DEMO_WORKSPACE_ID,
    environment: 'production',
    repositoryUrl: null,
    createdAt: '2026-01-10T09:00:00.000Z',
  },
  {
    id: 'user-service',
    name: 'user-service',
    description: 'Manages customer profiles and account data',
    status: 'healthy',
    teamId: 'team-identity',
    workspaceId: DEMO_WORKSPACE_ID,
    environment: 'production',
    repositoryUrl: null,
    createdAt: '2026-01-10T09:00:00.000Z',
  },
  {
    id: 'gateway',
    name: 'gateway',
    description: 'Routes external traffic to platform services',
    status: 'healthy',
    teamId: 'team-platform',
    workspaceId: DEMO_WORKSPACE_ID,
    environment: 'production',
    repositoryUrl: null,
    createdAt: '2026-01-10T09:00:00.000Z',
  },
  {
    id: 'notification-worker',
    name: 'notification-worker',
    description: 'Delivers transactional notifications',
    status: 'healthy',
    teamId: 'team-platform',
    workspaceId: DEMO_WORKSPACE_ID,
    environment: 'production',
    repositoryUrl: null,
    createdAt: '2026-01-10T09:00:00.000Z',
  },
  {
    id: 'web-storefront',
    name: 'web-storefront',
    description: 'Customer-facing commerce application',
    status: 'healthy',
    teamId: 'team-growth',
    workspaceId: DEMO_WORKSPACE_ID,
    environment: 'production',
    repositoryUrl: null,
    createdAt: '2026-01-10T09:00:00.000Z',
  },
  {
    id: 'analytics-api',
    name: 'analytics-api',
    description: 'Provides product analytics data',
    status: 'healthy',
    teamId: 'team-growth',
    workspaceId: DEMO_WORKSPACE_ID,
    environment: 'production',
    repositoryUrl: null,
    createdAt: '2026-01-10T09:00:00.000Z',
  },
  {
    id: 'search-api',
    name: 'search-api',
    description: 'Provides product search capabilities',
    status: 'healthy',
    teamId: 'team-growth',
    workspaceId: DEMO_WORKSPACE_ID,
    environment: 'production',
    repositoryUrl: null,
    createdAt: '2026-01-10T09:00:00.000Z',
  },
  {
    id: 'catalog-api',
    name: 'catalog-api',
    description: 'Manages product catalog information',
    status: 'healthy',
    teamId: 'team-growth',
    workspaceId: DEMO_WORKSPACE_ID,
    environment: 'production',
    repositoryUrl: null,
    createdAt: '2026-01-10T09:00:00.000Z',
  },
  {
    id: 'recommendation-service',
    name: 'recommendation-service',
    description: 'Generates product recommendations',
    status: 'maintenance',
    teamId: 'team-growth',
    workspaceId: DEMO_WORKSPACE_ID,
    environment: 'production',
    repositoryUrl: null,
    createdAt: '2026-01-10T09:00:00.000Z',
  },
])
